import { getDb } from "./firebase";
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { logger } from "./logger";
import { publishPost } from "../routes/social";
import { tickDrips } from "../routes/marketing";
import { tickNotifications } from "./notifications";
import { computePayrollRun } from "../routes/payroll";

const db = () => getDb();

const DEFAULT_PAYROLL_SETTINGS = {
  autoRunEnabled: false,
  autoRunDay: 1,
};

let started = false;
let timer: NodeJS.Timeout | null = null;
let running = false;

async function tick() {
  if (running) return;
  running = true;
  try {
    const now = Timestamp.now();
    const dueSnap = await db()
      .collection("socialPosts")
      .where("status", "==", "scheduled")
      .where("scheduledAt", "<=", now)
      .limit(10)
      .get();
    for (const doc of dueSnap.docs) {
      const post = { id: doc.id, ...doc.data() } as Record<string, unknown>;
      try {
        await publishPost(post.organizationId as string, doc.id);
      } catch (err) {
        logger.error({ err, postId: doc.id }, "Scheduled social publish failed");
      }
    }

    try {
      const r = await tickDrips();
      if (r.sent > 0) logger.info({ sent: r.sent }, "Drip tick sent emails");
    } catch (err) {
      logger.error({ err }, "Drip tick failed");
    }

    await tickNotifications();

    try {
      await tickPayrollAutoRuns();
    } catch (err) {
      logger.error({ err }, "Payroll auto-run tick failed");
    }
  } catch (err) {
    logger.error({ err }, "Scheduler tick failed");
  } finally {
    running = false;
  }
}

export async function tickPayrollAutoRuns(): Promise<{ created: number }> {
  const now = new Date();
  const today = now.getDate();
  const orgsSnap = await db().collection("organizations").get();
  let created = 0;

  const prev = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const periodMonth = prev.getMonth() + 1;
  const periodYear = prev.getFullYear();

  for (const orgDoc of orgsSnap.docs) {
    const org = orgDoc.data();
    const settings = { ...DEFAULT_PAYROLL_SETTINGS, ...(org.payrollSettings ?? {}) };
    if (!settings.autoRunEnabled) continue;
    if (!org.modules?.hr) continue;
    const day = Math.min(28, Math.max(1, Math.round(Number(settings.autoRunDay) || 1)));
    if (today < day) continue;

    const existingSnap = await db()
      .collection("payrollRuns")
      .where("organizationId", "==", orgDoc.id)
      .where("periodMonth", "==", periodMonth)
      .where("periodYear", "==", periodYear)
      .limit(1)
      .get();
    if (!existingSnap.empty) continue;

    try {
      const run = await computePayrollRun(orgDoc.id, periodMonth, periodYear, "Auto-generated by scheduler");
      created += 1;
      logger.info(
        { orgId: orgDoc.id, runId: run.id, periodMonth, periodYear },
        "Payroll auto-run created",
      );
    } catch (err) {
      logger.error({ err, orgId: orgDoc.id, periodMonth, periodYear }, "Payroll auto-run failed");
    }
  }
  return { created };
}

export function startScheduler(): void {
  if (started) return;
  started = true;
  timer = setInterval(() => {
    void tick();
  }, 60_000);
  setTimeout(() => void tick(), 5_000);
  logger.info("Round 4 scheduler started (social + drips)");
}

export function stopScheduler(): void {
  if (timer) clearInterval(timer);
  timer = null;
  started = false;
}
