import { db, socialPostsTable, organizationsTable, payrollRunsTable, DEFAULT_PAYROLL_SETTINGS } from "@workspace/db";
import { and, eq, lte, isNotNull } from "drizzle-orm";
import { logger } from "./logger";
import { publishPost } from "../routes/social";
import { tickDrips } from "../routes/marketing";
import { tickNotifications } from "./notifications";
import { computePayrollRun } from "../routes/payroll";

let started = false;
let timer: NodeJS.Timeout | null = null;
let running = false;

async function tick() {
  if (running) return;
  running = true;
  try {
    // Social: publish any scheduled post whose time has arrived.
    const due = await db
      .select()
      .from(socialPostsTable)
      .where(
        and(
          eq(socialPostsTable.status, "scheduled"),
          isNotNull(socialPostsTable.scheduledAt),
          lte(socialPostsTable.scheduledAt, new Date()),
        ),
      )
      .limit(10);
    for (const post of due) {
      try {
        await publishPost(post.organizationId, post.id);
      } catch (err) {
        logger.error({ err, postId: post.id }, "Scheduled social publish failed");
      }
    }
    // Drips
    try {
      const r = await tickDrips();
      if (r.sent > 0) logger.info({ sent: r.sent }, "Drip tick sent emails");
    } catch (err) {
      logger.error({ err }, "Drip tick failed");
    }
    // Push notifications (Round 6)
    await tickNotifications();
    // Auto-create monthly payroll runs.
    try {
      await tickPayrollAutoRuns();
    } catch (err) {
      logger.error({ err }, "Payroll auto-run tick failed");
    }
  } catch (err) {
    logger.error({ err }, "Scheduler tick failed");
  } finally {
    running = false;
  }
}

/**
 * Daily-ish payroll auto-run: for each org with `payrollSettings.autoRunEnabled`
 * and the HR module enabled, once the configured day-of-month is reached, draft
 * a payroll run for the previous calendar month (if one doesn't exist yet).
 * Dedup is via the unique (organizationId, periodMonth, periodYear) lookup in
 * the DB, so the 60s tick can keep firing safely.
 */
export async function tickPayrollAutoRuns(): Promise<{ created: number }> {
  const now = new Date();
  const today = now.getDate();
  const orgs = await db.select().from(organizationsTable);
  let created = 0;
  // Last calendar month
  const prev = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const periodMonth = prev.getMonth() + 1;
  const periodYear = prev.getFullYear();
  for (const org of orgs) {
    const settings = { ...DEFAULT_PAYROLL_SETTINGS, ...(org.payrollSettings ?? {}) };
    if (!settings.autoRunEnabled) continue;
    if (!org.modules?.hr) continue;
    const day = Math.min(28, Math.max(1, Math.round(Number(settings.autoRunDay) || 1)));
    if (today < day) continue;
    const [existing] = await db
      .select({ id: payrollRunsTable.id })
      .from(payrollRunsTable)
      .where(and(
        eq(payrollRunsTable.organizationId, org.id),
        eq(payrollRunsTable.periodMonth, periodMonth),
        eq(payrollRunsTable.periodYear, periodYear),
      ));
    if (existing) continue;
    try {
      const run = await computePayrollRun(org.id, periodMonth, periodYear, "Auto-generated by scheduler");
      created += 1;
      logger.info(
        { orgId: org.id, runId: run.id, periodMonth, periodYear },
        "Payroll auto-run created",
      );
    } catch (err) {
      logger.error({ err, orgId: org.id, periodMonth, periodYear }, "Payroll auto-run failed");
    }
  }
  return { created };
}

export function startScheduler(): void {
  if (started) return;
  started = true;
  // Run every 60 seconds.
  timer = setInterval(() => {
    void tick();
  }, 60_000);
  // Kick once shortly after boot.
  setTimeout(() => void tick(), 5_000);
  logger.info("Round 4 scheduler started (social + drips)");
}

export function stopScheduler(): void {
  if (timer) clearInterval(timer);
  timer = null;
  started = false;
}
