import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import organizationsRouter from "./organizations";
import clientsRouter from "./clients";
import productsRouter from "./products";
import addonsRouter from "./addons";
import quotationsRouter from "./quotations";
import reportsRouter from "./reports";
import smsRouter from "./sms";
import leadsRouter from "./leads";
import tasksRouter from "./tasks";
import callsRouter from "./calls";
import emailsRouter from "./emails";
import campaignsRouter from "./campaigns";
import salesOrdersRouter from "./sales-orders";
import invoicesRouter from "./invoices";
import paymentsRouter from "./payments";
import integrationsRouter from "./integrations";
import dashboardWidgetsRouter from "./dashboard-widgets";
import itemsRouter from "./items";
import warehousesRouter from "./warehouses";
import vendorsRouter from "./vendors";
import purchaseOrdersRouter from "./purchase-orders";
import grnRouter from "./grn";
import vendorBillsRouter from "./vendor-bills";
import inventoryRouter from "./inventory";
import socialRouter from "./social";
import marketingRouter from "./marketing";
import aiRouter from "./ai";
import reportsR4Router from "./reports-r4";
import uploadsRouter from "./uploads";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(organizationsRouter);
router.use(clientsRouter);
router.use(productsRouter);
router.use(addonsRouter);
router.use(quotationsRouter);
router.use(reportsRouter);
router.use(smsRouter);
router.use(leadsRouter);
router.use(tasksRouter);
router.use(callsRouter);
router.use(emailsRouter);
router.use(campaignsRouter);
router.use(salesOrdersRouter);
router.use(invoicesRouter);
router.use(paymentsRouter);
router.use(integrationsRouter);
router.use(dashboardWidgetsRouter);
router.use(itemsRouter);
router.use(warehousesRouter);
router.use(vendorsRouter);
router.use(purchaseOrdersRouter);
router.use(grnRouter);
router.use(vendorBillsRouter);
router.use(inventoryRouter);
router.use(socialRouter);
router.use(marketingRouter);
router.use(aiRouter);
router.use(reportsR4Router);
router.use(uploadsRouter);

export default router;
